name: Java CI

env:
  JDK_CURRENT: 17.0.10
  DISTRIBUTION: zulu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Setup JDK
        uses: actions/setup-java@215b7e5f829ab9cac114c149667e57dc1b70b4bc # v2
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: Build and test
        run: sbt clean +test
  publish:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Setup JDK
        uses: actions/setup-java@215b7e5f829ab9cac114c149667e57dc1b70b4bc # v2
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: Publish
        run: sbt +publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PWD }}
